azs:
- name: az1
  cpi: lab
  cloud_properties:
    datacenters:
    - clusters: [esxi-cluster01: {}]

vm_types:
- name: default
  cloud_properties:
    cpu: 1
    ram: 1024
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 20_240

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 20_000

compilation:
  workers: 2
  reuse_compilation_vms: true
  az: az1
  vm_type: default
  network: labnet

